"""Add access token

Revision ID: 743467eacb46
Revises: e0d1ecff916c
Create Date: 2024-08-12 16:08:08.661930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743467eacb46'
down_revision = 'e0d1ecff916c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_tokens',
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('access_token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_tokens')
    # ### end Alembic commands ###
